
package wsdl.stubs;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EngineService", targetNamespace = "http://tempuri.org/", wsdlLocation = "https://engine-externo.hml.anp.gov.br/engine_service.svc?singleWsdl")
public class EngineService
    extends Service
{

    private final static URL ENGINESERVICE_WSDL_LOCATION;
    private final static WebServiceException ENGINESERVICE_EXCEPTION;
    private final static QName ENGINESERVICE_QNAME = new QName("http://tempuri.org/", "EngineService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://engine-externo.hml.anp.gov.br/engine_service.svc?singleWsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ENGINESERVICE_WSDL_LOCATION = url;
        ENGINESERVICE_EXCEPTION = e;
    }

    public EngineService() {
        super(__getWsdlLocation(), ENGINESERVICE_QNAME);
    }

    public EngineService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ENGINESERVICE_QNAME, features);
    }

    public EngineService(URL wsdlLocation) {
        super(wsdlLocation, ENGINESERVICE_QNAME);
    }

    public EngineService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ENGINESERVICE_QNAME, features);
    }

    public EngineService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EngineService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IEngineService
     */
    @WebEndpoint(name = "BasicHttpsBinding_IEngineService")
    public IEngineService getBasicHttpsBindingIEngineService() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpsBinding_IEngineService"), IEngineService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IEngineService
     */
    @WebEndpoint(name = "BasicHttpsBinding_IEngineService")
    public IEngineService getBasicHttpsBindingIEngineService(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpsBinding_IEngineService"), IEngineService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ENGINESERVICE_EXCEPTION!= null) {
            throw ENGINESERVICE_EXCEPTION;
        }
        return ENGINESERVICE_WSDL_LOCATION;
    }

}
