
package wsdl.stubs;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IEngineService", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IEngineService {


    /**
     * 
     * @param informacaoAutenticacao
     * @param arquivo
     * @return
     *     returns wsdl.stubs.EnviarArquivoResponse.EnviarArquivoResult
     */
    @WebMethod(operationName = "EnviarArquivo", action = "http://tempuri.org/IEngineService/EnviarArquivo")
    @WebResult(name = "EnviarArquivoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "EnviarArquivo", targetNamespace = "http://tempuri.org/", className = "wsdl.stubs.EnviarArquivo")
    @ResponseWrapper(localName = "EnviarArquivoResponse", targetNamespace = "http://tempuri.org/", className = "wsdl.stubs.EnviarArquivoResponse")
    public wsdl.stubs.EnviarArquivoResponse.EnviarArquivoResult enviarArquivo(
        @WebParam(name = "arquivo", targetNamespace = "http://tempuri.org/")
        Arquivo arquivo,
        @WebParam(name = "informacaoAutenticacao", targetNamespace = "http://tempuri.org/")
        InformacaoAutenticacao informacaoAutenticacao);

    /**
     * 
     * @param protocolo
     * @param informacaoAutenticacao
     * @return
     *     returns wsdl.stubs.RetornarLogProcessamentoResponse.RetornarLogProcessamentoResult
     */
    @WebMethod(operationName = "RetornarLogProcessamento", action = "http://tempuri.org/IEngineService/RetornarLogProcessamento")
    @WebResult(name = "RetornarLogProcessamentoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RetornarLogProcessamento", targetNamespace = "http://tempuri.org/", className = "wsdl.stubs.RetornarLogProcessamento")
    @ResponseWrapper(localName = "RetornarLogProcessamentoResponse", targetNamespace = "http://tempuri.org/", className = "wsdl.stubs.RetornarLogProcessamentoResponse")
    public wsdl.stubs.RetornarLogProcessamentoResponse.RetornarLogProcessamentoResult retornarLogProcessamento(
        @WebParam(name = "protocolo", targetNamespace = "http://tempuri.org/")
        String protocolo,
        @WebParam(name = "informacaoAutenticacao", targetNamespace = "http://tempuri.org/")
        InformacaoAutenticacao informacaoAutenticacao);

    /**
     * 
     * @param protocolo
     * @param informacaoAutenticacao
     * @return
     *     returns wsdl.stubs.RetornarSituacaoArquivoResponse.RetornarSituacaoArquivoResult
     */
    @WebMethod(operationName = "RetornarSituacaoArquivo", action = "http://tempuri.org/IEngineService/RetornarSituacaoArquivo")
    @WebResult(name = "RetornarSituacaoArquivoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RetornarSituacaoArquivo", targetNamespace = "http://tempuri.org/", className = "wsdl.stubs.RetornarSituacaoArquivo")
    @ResponseWrapper(localName = "RetornarSituacaoArquivoResponse", targetNamespace = "http://tempuri.org/", className = "wsdl.stubs.RetornarSituacaoArquivoResponse")
    public wsdl.stubs.RetornarSituacaoArquivoResponse.RetornarSituacaoArquivoResult retornarSituacaoArquivo(
        @WebParam(name = "protocolo", targetNamespace = "http://tempuri.org/")
        String protocolo,
        @WebParam(name = "informacaoAutenticacao", targetNamespace = "http://tempuri.org/")
        InformacaoAutenticacao informacaoAutenticacao);

    /**
     * 
     * @param informacaoAutenticacao
     * @param nomeArquivo
     * @return
     *     returns wsdl.stubs.RetornarProtolocoArquivoResponse.RetornarProtolocoArquivoResult
     */
    @WebMethod(operationName = "RetornarProtolocoArquivo", action = "http://tempuri.org/IEngineService/RetornarProtolocoArquivo")
    @WebResult(name = "RetornarProtolocoArquivoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RetornarProtolocoArquivo", targetNamespace = "http://tempuri.org/", className = "wsdl.stubs.RetornarProtolocoArquivo")
    @ResponseWrapper(localName = "RetornarProtolocoArquivoResponse", targetNamespace = "http://tempuri.org/", className = "wsdl.stubs.RetornarProtolocoArquivoResponse")
    public wsdl.stubs.RetornarProtolocoArquivoResponse.RetornarProtolocoArquivoResult retornarProtolocoArquivo(
        @WebParam(name = "nomeArquivo", targetNamespace = "http://tempuri.org/")
        String nomeArquivo,
        @WebParam(name = "informacaoAutenticacao", targetNamespace = "http://tempuri.org/")
        InformacaoAutenticacao informacaoAutenticacao);

}
